apiVersion: v1
kind: Endpoints
metadata:
  name: echo
  namespace: datadog
  labels:
    app: echo
subsets:
- addresses:
  - ip: 172.21.32.117
  ports:
  - name: http
    port: 5000
    protocol: TCP
